/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.City;
import model.Encounter;
import model.EncounterHistory;
import model.PatientDirectory;
import model.VitalSigns;

/**
 *
 * @author namita
 */
public class NewEncounterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewEncounterJPanel
     */
    PatientDirectory history;
    City city;
    public NewEncounterJPanel(PatientDirectory history,City city) {
        this.history = history;
        this.city=city;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblPulseRate = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        txtBodyTemperature = new javax.swing.JTextField();
        txtPulseRate = new javax.swing.JTextField();
        txtRespiration = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Add New Vitals for Existing Patient");

        lblPatientID.setText("Patient ID :");

        lblBloodPressure.setText("Blood Pressure :");

        lblWeight.setText("Body Temperature :");

        lblPulseRate.setText("Pulse Rate :");

        lblHeartRate.setText("Respiration :");

        txtPatientID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPatientIDKeyReleased(evt);
            }
        });

        txtBodyTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodyTemperatureActionPerformed(evt);
            }
        });

        txtPulseRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPulseRateActionPerformed(evt);
            }
        });

        txtRespiration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespirationActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBloodPressure)
                            .addComponent(lblWeight)
                            .addComponent(lblPulseRate)
                            .addComponent(lblHeartRate))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPatientID, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(txtBloodPressure)
                                    .addComponent(txtBodyTemperature)
                                    .addComponent(txtPulseRate)
                                    .addComponent(txtRespiration))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientID)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBloodPressure)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeight)
                            .addComponent(txtBodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPulseRate)
                            .addComponent(txtPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHeartRate)
                            .addComponent(txtRespiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBodyTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodyTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBodyTemperatureActionPerformed

    private void txtPulseRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPulseRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPulseRateActionPerformed

    private void txtRespirationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespirationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespirationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Integer id = Integer.parseInt(txtPatientID.getText());
         
        Integer bp = Integer.parseInt(txtBloodPressure.getText());
      Integer pulse = Integer.parseInt(txtPulseRate.getText());
      Integer bt = Integer.parseInt(txtBodyTemperature.getText());
      Integer respiration = Integer.parseInt(txtRespiration.getText());
    String timestamp = new SimpleDateFormat("MM/dd/yyyy").format(Calendar.getInstance().getTime());

  //chup   Person patient = history.addNewPerson();
      ///////////////////////////////////////////////////////////////////////////////////////
//DefaultTableModel model = (DefaultTableModel)tblPatient.getModel();

for(int i=0; i<history.getpatientDirectory().size(); i++)
{
   int patientid = (history.getpatientDirectory().get(i).getPatientID());
    if(id == patientid)
    {
      EncounterHistory eh=history.getpatientDirectory().get(i).getEncounterHistory();
      VitalSigns vs=new VitalSigns(respiration,pulse,bp,bt);
      Encounter encounter=new Encounter("01/01/2020",vs);
       eh.addNewEncounter(encounter);
    

JOptionPane.showMessageDialog(this,"New vitals added for the patient.");
      
     
      txtPatientID.setText("");
      txtBloodPressure.setText("");
      txtPulseRate.setText("");
      txtBodyTemperature.setText("");
      txtRespiration.setText("");
}  
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPatientIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientIDKeyReleased
        // TODO add your handling code here:
        String checkAge=txtPatientID.getText();

        Pattern pattern=Pattern.compile("^[0-9]{1,10}$");



        Matcher matchPattern=pattern.matcher(checkAge);
        if(!matchPattern.matches())
        {
        jLabel2.setText("Please Enter Valid Patient ID." );

        }
        else{
        jLabel2.setText(null);
        }
    }//GEN-LAST:event_txtPatientIDKeyReleased
private void txtBloodPressureKeyReleased(java.awt.event.KeyEvent evt) {                                             
        // TODO add your handling code here:
        String checkAge=txtBloodPressure.getText();

        Pattern pattern=Pattern.compile("^[0-9]{1,2}$");



        Matcher matchPattern=pattern.matcher(checkAge);
        if(!matchPattern.matches())
        {
        jLabel3.setText("Please Enter Valid BP." );

        }
        else{
        jLabel3.setText(null);
        }
    }                                            

    private void txtBodyTemperatureKeyReleased(java.awt.event.KeyEvent evt) {                                               
        // TODO add your handling code here:
        String checkAge=txtBodyTemperature.getText();

        Pattern pattern=Pattern.compile("^[0-9]{1,2}$");



        Matcher matchPattern=pattern.matcher(checkAge);
        if(!matchPattern.matches())
        {
        jLabel4.setText("Please Enter Valid Temperature." );

        }
        else{
        jLabel4.setText(null);
        }
    }                                              

    private void txtPulseRateKeyReleased(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
         String checkAge=txtPulseRate.getText();

        Pattern pattern=Pattern.compile("^[0-9]{1,2}$");



        Matcher matchPattern=pattern.matcher(checkAge);
        if(!matchPattern.matches())
        {
        jLabel5.setText("Please Enter Valid Pulse Rate." );

        }
        else{
        jLabel5.setText(null);
        }
    }                                        

    private void txtRespirationKeyReleased(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
        String checkAge=txtRespiration.getText();

        Pattern pattern=Pattern.compile("^[0-9]{1,2}$");



        Matcher matchPattern=pattern.matcher(checkAge);
        if(!matchPattern.matches())
        {
        jLabel6.setText("Please Enter Valid Respiration." );

        }
        else{
        jLabel6.setText(null);
        }
    }         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPulseRate;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtBodyTemperature;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPulseRate;
    private javax.swing.JTextField txtRespiration;
    // End of variables declaration//GEN-END:variables

private void populateTable() {
        
        
    }
}
