/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.History;
import model.Vehicle;

/**
 *
 * @author namita
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    History history;
    DefaultTableModel model;
    
    public SearchPanel(History history) {
        initComponents();
        this.history = history;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnfirst_available_car = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        btnall_manufacturers = new javax.swing.JButton();
        lblcar_make = new javax.swing.JLabel();
        lblmanufacturing_year = new javax.swing.JLabel();
        lblserial_number = new javax.swing.JLabel();
        lblmodel_number = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblseat_count = new javax.swing.JLabel();
        cbmin = new javax.swing.JComboBox<>();
        cbmax = new javax.swing.JComboBox<>();
        chkavailable = new javax.swing.JCheckBox();
        chkcertificate_expired = new javax.swing.JCheckBox();
        txtsearchCarMake = new javax.swing.JTextField();
        txtsearchManufacturingYear = new javax.swing.JTextField();
        txtsearchSerialNumber = new javax.swing.JTextField();
        txtsearchModelNumber = new javax.swing.JTextField();
        txtsearchCity = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblLastUpdated = new javax.swing.JLabel();
        txtLastUpdated = new javax.swing.JTextField();
        btnTotalCars = new javax.swing.JButton();
        btnAvailableCars = new javax.swing.JButton();
        btnNotAvailableCar = new javax.swing.JButton();
        txtTotalCars = new javax.swing.JTextField();
        txtAvailableCars = new javax.swing.JTextField();
        txtNotAvailableCars = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 153, 153));

        btnfirst_available_car.setBackground(new java.awt.Color(153, 153, 153));
        btnfirst_available_car.setText("First Available Passenger Car ");
        btnfirst_available_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirst_available_carActionPerformed(evt);
            }
        });

        tblVehicles.setBackground(new java.awt.Color(204, 204, 204));
        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Car Make", "Manufacturing Year", "Serial Number", "Model Number", "City", "Seats", "Is available?", "Is maintenance valid?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVehicles);

        btnall_manufacturers.setBackground(new java.awt.Color(153, 153, 153));
        btnall_manufacturers.setText("All Manufacturers used by Uber ");
        btnall_manufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnall_manufacturersActionPerformed(evt);
            }
        });

        lblcar_make.setText("Car Make :");

        lblmanufacturing_year.setText("Manufacturing Year :");

        lblserial_number.setText("Serial Number :");

        lblmodel_number.setText("Model Number :");

        lblcity.setText("City :");

        lblseat_count.setText("Seats :");

        cbmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));
        cbmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbminActionPerformed(evt);
            }
        });

        cbmax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));

        chkavailable.setText("Is Available ?");

        chkcertificate_expired.setText("Is Certificate Expired ?");

        txtsearchCarMake.setBackground(new java.awt.Color(255, 204, 204));

        txtsearchManufacturingYear.setBackground(new java.awt.Color(255, 204, 204));

        txtsearchSerialNumber.setBackground(new java.awt.Color(255, 204, 204));

        txtsearchModelNumber.setBackground(new java.awt.Color(255, 204, 204));

        txtsearchCity.setBackground(new java.awt.Color(255, 204, 204));
        txtsearchCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchCityActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblLastUpdated.setText("Last Updated :");

        btnTotalCars.setText("Total Cars :");
        btnTotalCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalCarsActionPerformed(evt);
            }
        });

        btnAvailableCars.setText("Available Cars :");
        btnAvailableCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableCarsActionPerformed(evt);
            }
        });

        btnNotAvailableCar.setText("Not available Cars :");
        btnNotAvailableCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotAvailableCarActionPerformed(evt);
            }
        });

        txtTotalCars.setBackground(new java.awt.Color(255, 204, 204));

        txtAvailableCars.setBackground(new java.awt.Color(255, 204, 204));

        txtNotAvailableCars.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(297, 297, 297))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblmanufacturing_year)
                                    .addComponent(lblcar_make)
                                    .addComponent(lblserial_number)
                                    .addComponent(lblmodel_number)
                                    .addComponent(lblcity)
                                    .addComponent(lblseat_count)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(lblLastUpdated)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbmin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbmax, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtsearchCarMake, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtsearchManufacturingYear)
                                    .addComponent(txtsearchSerialNumber)
                                    .addComponent(txtsearchModelNumber)
                                    .addComponent(txtsearchCity))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkavailable)
                                            .addComponent(chkcertificate_expired))
                                        .addGap(41, 41, 41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnAvailableCars)
                                            .addComponent(btnTotalCars)
                                            .addComponent(btnNotAvailableCar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTotalCars, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                            .addComponent(txtAvailableCars)
                                            .addComponent(txtNotAvailableCars))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnall_manufacturers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(btnfirst_available_car, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnfirst_available_car)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnall_manufacturers, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblcar_make)
                                    .addComponent(txtsearchCarMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkavailable))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(lblmanufacturing_year))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(chkcertificate_expired))))
                            .addComponent(txtsearchManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblserial_number)
                            .addComponent(txtsearchSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTotalCars)
                            .addComponent(txtTotalCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvailableCars)
                    .addComponent(txtAvailableCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmodel_number)
                    .addComponent(txtsearchModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNotAvailableCar)
                    .addComponent(txtNotAvailableCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity)
                    .addComponent(txtsearchCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblseat_count))
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastUpdated)
                    .addComponent(txtLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbminActionPerformed

    private void txtsearchCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchCityActionPerformed

    private void btnfirst_available_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirst_available_carActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
        model.setRowCount(0);
        for(Vehicle v: history.getCatalog()){
        Object[] row=new Object[10];
        row[0]=v;
                if(v.isAvailability()==true){
                row[1]=v.getCarMake();
        row[2]=v.getManufacturingYear();
        row[3]=v.getSerialNumber();
        row[4]=v.getModelNumber();
        row[6]=v.getSeatCount();
        row[7]=v.isAvailability();
        row[8]=v.isMaintenanceExpired();
        row[5]=v.getCity();
                model.addRow(row);
                break;
        }
        }
    }//GEN-LAST:event_btnfirst_available_carActionPerformed

    private void btnall_manufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnall_manufacturersActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
        model.setRowCount(0);
        ArrayList<String> num = new ArrayList<String>();

        for(Vehicle car: history.getCatalog()){
        Object[] row=new Object[10];
       if(! num.contains(car.getCarMake())){
           num.add((car.getCarMake()));
                row[1]=car.getCarMake();
                    model.addRow(row);
       }
        }
        
        
    }//GEN-LAST:event_btnall_manufacturersActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        String mfBy= txtsearchCarMake.getText();
       String mfYr= txtsearchManufacturingYear.getText();
     String GeoLocation=   txtsearchCity.getText();

      Byte lowSeats=   Byte.parseByte(cbmin.getSelectedItem().toString());
      Byte highSeats=   Byte.parseByte(cbmax.getSelectedItem().toString());

      String SerialNumber=   txtsearchSerialNumber.getText() ;
     String ModelNumber=  txtsearchModelNumber.getText();
    Boolean availablity=  chkavailable.isSelected();
     Boolean certification=   chkcertificate_expired.isSelected();
   System.out.println(lowSeats);
        System.out.println(highSeats);


        DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
        model.setRowCount(0);
        for(Vehicle car: history.getCatalog()){
        Object[] row=new Object[10];
        
        row[0]=car;

        if(mfBy.length()==0 || car.getCarMake().equals(mfBy) ){
            if(mfYr.length()==0 || car.getManufacturingYear()==Integer.parseInt(mfYr)){
            if(SerialNumber.length()==0 || car.getSerialNumber().equals(SerialNumber)){
            if(GeoLocation.length()==0 || car.getCity().equals(GeoLocation)){
             if((lowSeats==0 && highSeats==0) || (car.getSeatCount()>=lowSeats &&car.getSeatCount()<=highSeats)){
            if(ModelNumber.length()==0  || car.getModelNumber().equals(ModelNumber)){
            if(availablity==false || car.isAvailability()==availablity){
            if(certification==false || car.isMaintenanceExpired()==certification){
        row[1]=car.getCarMake();
        row[2]=car.getManufacturingYear();
        row[3]=car.getSerialNumber();
        row[4]=car.getModelNumber();
        row[6]=car.getSeatCount();
        row[7]=car.isAvailability();
        row[8]=car.isMaintenanceExpired();
        row[5]=car.getCity();
                model.addRow(row);

        }
        }
        }
        }
        }
        }
        }
        }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAvailableCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableCarsActionPerformed
        // TODO add your handling code here:
        
        int sum = 0;
        if (history.getCatalog().size()>0){
            for(Vehicle car: history.getCatalog()){
                if(car.isAvailability()==true){
                    sum=sum+1;
                }
            }
        }
        txtAvailableCars.setText(String.valueOf(sum));
        
    }//GEN-LAST:event_btnAvailableCarsActionPerformed

    private void btnTotalCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalCarsActionPerformed
        // TODO add your handling code here:
        int totalCars = history.getCatalog().size();
        txtTotalCars.setText(String.valueOf(totalCars));
    }//GEN-LAST:event_btnTotalCarsActionPerformed

    private void btnNotAvailableCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotAvailableCarActionPerformed
        // TODO add your handling code here:
        
         int sum = 0;
        if (history.getCatalog().size()>0){
            for(Vehicle car: history.getCatalog()){
                if(car.isAvailability()==false){
                    sum=sum+1;
                }
            }
        }
        txtNotAvailableCars.setText(String.valueOf(sum));
        
    }//GEN-LAST:event_btnNotAvailableCarActionPerformed

        private void populateTable() {
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  

        txtLastUpdated.setText(formatter.format(history.getLast_Updated()));
        DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
        model.setRowCount(0);
        for(Vehicle car: history.getCatalog()){
        Object[] row=new Object[10];
        row[0]=car;
        row[1]=car.getCarMake();
        row[2]=car.getManufacturingYear();
        row[3]=car.getSerialNumber();
        row[4]=car.getModelNumber();
        row[6]=car.getSeatCount();
        row[7]=car.isAvailability();
        row[8]=car.isMaintenanceExpired();
        row[5]=car.getCity();
//        row[5]=car.getName();
        model.addRow(row);
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailableCars;
    private javax.swing.JButton btnNotAvailableCar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTotalCars;
    private javax.swing.JButton btnall_manufacturers;
    private javax.swing.JButton btnfirst_available_car;
    private javax.swing.JComboBox<String> cbmax;
    private javax.swing.JComboBox<String> cbmin;
    private javax.swing.JCheckBox chkavailable;
    private javax.swing.JCheckBox chkcertificate_expired;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JLabel lblcar_make;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblmanufacturing_year;
    private javax.swing.JLabel lblmodel_number;
    private javax.swing.JLabel lblseat_count;
    private javax.swing.JLabel lblserial_number;
    private javax.swing.JTable tblVehicles;
    private javax.swing.JTextField txtAvailableCars;
    private javax.swing.JTextField txtLastUpdated;
    private javax.swing.JTextField txtNotAvailableCars;
    private javax.swing.JTextField txtTotalCars;
    private javax.swing.JTextField txtsearchCarMake;
    private javax.swing.JTextField txtsearchCity;
    private javax.swing.JTextField txtsearchManufacturingYear;
    private javax.swing.JTextField txtsearchModelNumber;
    private javax.swing.JTextField txtsearchSerialNumber;
    // End of variables declaration//GEN-END:variables
}
