/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static javax.xml.catalog.CatalogManager.catalog;
import model.History;
import model.Vehicle;

/**
 *
 * @author namita
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    History history;
    
    public ViewPanel(History history) {
        initComponents();
        this.history = history;
        
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtseatCount = new javax.swing.JTextField();
        lblmanufacturingYear = new javax.swing.JLabel();
        txtserialNumber = new javax.swing.JTextField();
        lblseatCount = new javax.swing.JLabel();
        lblserialNumber = new javax.swing.JLabel();
        chkavailability = new javax.swing.JCheckBox();
        lblmaintenanceDate = new javax.swing.JLabel();
        txtcarMake = new javax.swing.JTextField();
        txtmodelNumber = new javax.swing.JTextField();
        lblcarMake = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lblmodelNumber = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblavailability = new javax.swing.JLabel();
        txtmanufacturingYear = new javax.swing.JTextField();
        lblLastUpdated = new javax.swing.JLabel();
        txtLastUpdated = new javax.swing.JTextField();
        chkmaintenanceExpired = new javax.swing.JCheckBox();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setText("View Catalogue");

        tblVehicles.setBackground(new java.awt.Color(204, 204, 204));
        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Car Make", "Manufacturing Year", "Serial Number", "Model Number", "City", "Seats", "Is available?", "Is maintenance valid?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVehicles);

        btnViewDetails.setBackground(new java.awt.Color(204, 204, 204));
        btnViewDetails.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnViewDetails.setText("Edit Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtseatCount.setBackground(new java.awt.Color(255, 204, 204));

        lblmanufacturingYear.setText("Manufacturing Year :");

        txtserialNumber.setBackground(new java.awt.Color(255, 204, 204));

        lblseatCount.setText("Seat Count :");

        lblserialNumber.setText("Serial Number :");

        lblmaintenanceDate.setText("Maintenance Expired? :");

        txtcarMake.setBackground(new java.awt.Color(255, 204, 204));

        txtmodelNumber.setBackground(new java.awt.Color(255, 204, 204));

        lblcarMake.setText("Car Make : ");

        txtcity.setBackground(new java.awt.Color(255, 204, 204));

        lblmodelNumber.setText("Model Number : ");

        lblcity.setText("City :");

        lblavailability.setText("Availability :");

        txtmanufacturingYear.setBackground(new java.awt.Color(255, 204, 204));

        lblLastUpdated.setText("Last Updated : ");

        txtLastUpdated.setBackground(new java.awt.Color(255, 204, 204));

        lblname.setText("Name :");

        txtname.setBackground(new java.awt.Color(255, 204, 204));

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(274, 274, 274)
                                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewDetails)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblseatCount)
                                    .addComponent(lblmaintenanceDate)
                                    .addComponent(lblserialNumber)
                                    .addComponent(lblmanufacturingYear)
                                    .addComponent(lblavailability)
                                    .addComponent(lblcity)
                                    .addComponent(lblmodelNumber)
                                    .addComponent(lblcarMake))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(btnUpdate))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtseatCount, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtmanufacturingYear, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtcity, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtmodelNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkavailability, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkmaintenanceExpired, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtcarMake, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtserialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnViewDetails)
                            .addComponent(btnDelete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastUpdated)
                            .addComponent(txtLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcarMake)
                    .addComponent(txtcarMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmodelNumber)
                    .addComponent(txtmodelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblavailability)
                    .addComponent(chkavailability))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmanufacturingYear)
                    .addComponent(txtmanufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblseatCount)
                    .addComponent(txtseatCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblserialNumber)
                    .addComponent(txtserialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmaintenanceDate)
                    .addComponent(chkmaintenanceExpired))
                .addGap(11, 11, 11)
                .addComponent(btnUpdate)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblVehicles.getSelectedRow();
        
        if (selectedRowIndex<0){
        
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;        
        }
        
        DefaultTableModel model = (DefaultTableModel)tblVehicles.getModel();
        Vehicle selectedVehicle = (Vehicle) model.getValueAt(selectedRowIndex, 0);
        history.deleteCar(selectedVehicle);
        
        JOptionPane.showMessageDialog(this, "Vehicle deleted.");
        populateTable();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
        Date date = new Date();  
        history.setLast_Updated(date);
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
       int selectedRowIndex = tblVehicles.getSelectedRow();
        
        if (selectedRowIndex<0){
        
            JOptionPane.showMessageDialog(this, "Please select a row to view details.");
            return;
            
            
        }
        
        DefaultTableModel model = (DefaultTableModel)tblVehicles.getModel();
        //Vehicle selectedVehicle = (Vehicle) model.getValueAt(selectedRowIndex, 0);
        
        txtname.setText(String.valueOf(model.getValueAt(selectedRowIndex, 0)));
        txtcarMake.setText(String.valueOf(model.getValueAt(selectedRowIndex, 1)));
        txtmanufacturingYear.setText(String.valueOf(model.getValueAt(selectedRowIndex, 2)));
        txtcity.setText(String.valueOf(model.getValueAt(selectedRowIndex, 5)));
        txtmodelNumber.setText(String.valueOf(model.getValueAt(selectedRowIndex, 4)));
        txtserialNumber.setText(String.valueOf(model.getValueAt(selectedRowIndex, 3)));
        chkavailability.setSelected(Boolean.valueOf(model.getValueAt(selectedRowIndex, 7).toString()));
        chkmaintenanceExpired.setSelected(Boolean.valueOf(model.getValueAt(selectedRowIndex, 8).toString()));
        txtseatCount.setText(String.valueOf(String.valueOf(model.getValueAt(selectedRowIndex, 6))));       
        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
        int selectedRowIndex=tblVehicles.getSelectedRow();
         if(selectedRowIndex<0){
             JOptionPane.showMessageDialog(this, "Please select a row to delete");
         }
        DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
        Vehicle selectedCar=(Vehicle) model.getValueAt(selectedRowIndex,0);
       selectedCar.setName(txtname.getText());
       selectedCar.setCarMake(txtcarMake.getText());
       selectedCar.setManufacturingYear(Integer.parseInt(txtmanufacturingYear.getText()));
       selectedCar.setCity(txtcity.getText());
       selectedCar.setSeatCount(Byte.parseByte(txtseatCount.getText()));
       selectedCar.setSerialNumber(txtserialNumber.getText() );
       selectedCar.setModelNumber(txtmodelNumber.getText());
       selectedCar.setAvailability(chkavailability.isSelected());
       selectedCar.setMaintenanceExpired(chkmaintenanceExpired.isSelected());
       JOptionPane.showMessageDialog(this, "entry has been updated");
     SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
    Date date = new Date();  
    history.setLast_Updated(date);
            txtLastUpdated.setText(formatter.format(history.getLast_Updated()));
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JCheckBox chkavailability;
    private javax.swing.JCheckBox chkmaintenanceExpired;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblavailability;
    private javax.swing.JLabel lblcarMake;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblmaintenanceDate;
    private javax.swing.JLabel lblmanufacturingYear;
    private javax.swing.JLabel lblmodelNumber;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblseatCount;
    private javax.swing.JLabel lblserialNumber;
    private javax.swing.JTable tblVehicles;
    private javax.swing.JTextField txtLastUpdated;
    private javax.swing.JTextField txtcarMake;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtmanufacturingYear;
    private javax.swing.JTextField txtmodelNumber;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtseatCount;
    private javax.swing.JTextField txtserialNumber;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
        model.setRowCount(0);
        for(Vehicle v: history.getCatalog()){
        Object[] row=new Object[10];
        row[0]=v;
        row[1]=v.getCarMake();
        row[2]=v.getManufacturingYear();
        row[3]=v.getSerialNumber();
        row[4]=v.getModelNumber();
        row[6]=v.getSeatCount();
        row[7]=v.isAvailability();
        row[8]=v.isMaintenanceExpired();
        row[5]=v.getCity();
        
        model.addRow(row);
        }
    }
}
