/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;

/**
 *
 * @author namita
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Person person;
    
    public CreateJPanel(Person person) {
        initComponents();
        
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblDoB = new javax.swing.JLabel();
        lblPhNo = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lblMedicalNo = new javax.swing.JLabel();
        lblHealthPlanNo = new javax.swing.JLabel();
        lblBankAccNo = new javax.swing.JLabel();
        lblCertificateNo = new javax.swing.JLabel();
        lblVehicleIdentifier = new javax.swing.JLabel();
        lblDeviceIdentifier = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblipaddress = new javax.swing.JLabel();
        lbluidCode = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhNo = new javax.swing.JTextField();
        txtFaxNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtMedicalNo = new javax.swing.JTextField();
        txtHealthPlanNo = new javax.swing.JTextField();
        txtBankAccNo = new javax.swing.JTextField();
        txtCertificateNo = new javax.swing.JTextField();
        txtVehicleIdentifier = new javax.swing.JTextField();
        txtDeviceIdentifier = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtipaddress = new javax.swing.JTextField();
        txtuid = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnPhoto = new javax.swing.JButton();
        jPhoto = new javax.swing.JLabel();
        jDate = new com.toedter.calendar.JDateChooser();

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create");

        lblName.setText("Name : ");

        lblAddress.setText("Address : ");

        lblDoB.setText("DoB :");

        lblPhNo.setText("Ph No :");

        lblFax.setText("Fax No :");

        lblEmail.setText("Email :");

        lblssn.setText("SSN : ");

        lblMedicalNo.setText("Medical No: ");

        lblHealthPlanNo.setText("Health Plan No :");

        lblBankAccNo.setText("Bank Account No :");

        lblCertificateNo.setText("Certificate/License No :");

        lblVehicleIdentifier.setText("Vehicle identifier :");

        lblDeviceIdentifier.setText("Device Identifier : ");

        lblLinkedIn.setText("LinkedIn :");

        lblipaddress.setText("IP Address : ");

        lbluidCode.setText("UID/Code :");

        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAddressFocusLost(evt);
            }
        });
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtPhNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhNoFocusLost(evt);
            }
        });
        txtPhNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhNoActionPerformed(evt);
            }
        });

        txtFaxNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFaxNoFocusLost(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtssn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtssnFocusLost(evt);
            }
        });
        txtssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtssnActionPerformed(evt);
            }
        });

        txtMedicalNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMedicalNoFocusLost(evt);
            }
        });
        txtMedicalNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalNoActionPerformed(evt);
            }
        });

        txtHealthPlanNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHealthPlanNoFocusLost(evt);
            }
        });

        txtBankAccNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBankAccNoFocusLost(evt);
            }
        });

        txtCertificateNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCertificateNoFocusLost(evt);
            }
        });

        txtVehicleIdentifier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVehicleIdentifierFocusLost(evt);
            }
        });

        txtDeviceIdentifier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeviceIdentifierFocusLost(evt);
            }
        });

        txtLinkedIn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLinkedInFocusLost(evt);
            }
        });

        txtipaddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtipaddressFocusLost(evt);
            }
        });

        txtuid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuidFocusLost(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnPhoto.setText("Upload Photo");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        jPhoto.setText("jPhoto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDoB)
                                    .addComponent(lblAddress)
                                    .addComponent(lblName))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblipaddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLinkedIn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDeviceIdentifier, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCertificateNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVehicleIdentifier, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBankAccNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHealthPlanNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMedicalNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblssn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFax, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPhNo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(txtAddress)
                            .addComponent(txtPhNo)
                            .addComponent(txtFaxNo)
                            .addComponent(txtEmail)
                            .addComponent(txtssn)
                            .addComponent(txtMedicalNo)
                            .addComponent(txtHealthPlanNo)
                            .addComponent(txtBankAccNo)
                            .addComponent(txtCertificateNo)
                            .addComponent(txtVehicleIdentifier)
                            .addComponent(txtDeviceIdentifier)
                            .addComponent(txtLinkedIn)
                            .addComponent(txtipaddress)
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPhoto)
                            .addComponent(lbluidCode))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPhoto)
                            .addComponent(txtuid, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblTitle)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDoB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblssn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicalNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicalNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHealthPlanNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHealthPlanNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBankAccNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleIdentifier)
                    .addComponent(txtVehicleIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCertificateNo)
                    .addComponent(txtCertificateNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeviceIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeviceIdentifier))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkedIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtipaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblipaddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluidCode)
                    .addComponent(txtuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPhoto)
                    .addComponent(jPhoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtssnActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        person.setName(txtName.getText());
        person.setAddress(txtAddress.getText());
        person.setDoB(jDate.getDate());
        person.setPhNo(Long.valueOf(txtPhNo.getText()));
        person.setFaxNo(txtFaxNo.getText());
        person.setEmail(txtEmail.getText());
        person.setssn(txtssn.getText());
        person.setMedicalNo(txtMedicalNo.getText());
        person.setHealthPlanNo(txtHealthPlanNo.getText());
        person.setBankAccNo(txtBankAccNo.getText());
        person.setCertificateNo(txtCertificateNo.getText());
        person.setVehicleIdentifier(txtVehicleIdentifier.getText());
        person.setDeviceidentifier(txtDeviceIdentifier.getText());
        person.setLinkedIn(txtLinkedIn.getText());
        person.setipaddress(txtipaddress.getText());
        person.setuidcode(txtuid.getText());
        
        
        
        
        
        JOptionPane.showMessageDialog(this,"Information Saved ! ");
       // JOptionPane.showMessageDialog(this,"Person information is saved.");
        
         
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser photo = new JFileChooser();  
         
       // FileNameExtensionFilter filter = new FileNameExtensionFilter("2 extensions supported", "jpg", "png" );
        //photo.setFileFilter(filter);
        
        //int selected = photo.showOpenDialog(null);
        //if (selected == JFileChooser.APPROVE_OPTION)
        //{
        // File file = photo.getSelectedFile();
        // String getselectedImage = file.getAbsolutePath();
        // JOptionPane.showMessageDialog(null,getselectedImage);
         
         
        //}        
       photo.showOpenDialog(null);
        File chooseFile = photo.getSelectedFile();
        
        person.setPhoto(chooseFile);
        
        
    }//GEN-LAST:event_btnPhotoActionPerformed

    private void txtPhNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhNoActionPerformed

    private void txtPhNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhNoFocusLost


    String chckNo=txtPhNo.getText();

    Pattern pattern = Pattern.compile("^[0-9]{10}$");
    Matcher matchPattern=pattern.matcher(chckNo);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid Ph No. ! ");   
    }

    // TODO add your handling code here:
    }//GEN-LAST:event_txtPhNoFocusLost

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
       
        String chckName=txtName.getText();

    Pattern pattern = Pattern.compile("^[a-zA-Z-]{1,50}$");
    Matcher matchPattern=pattern.matcher(chckName);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a name ! ");   
    }// TODO add your handling code here:
    }//GEN-LAST:event_txtNameFocusLost

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAddressFocusLost
    String chckAddress=txtAddress.getText();

    Pattern pattern = Pattern.compile("^[a-zA-Z0-9-, ]{1,50}$");
    Matcher matchPattern=pattern.matcher(chckAddress);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid address(no characters allowed) ! ");   
    }// TODO  // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressFocusLost

    private void txtFaxNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFaxNoFocusLost
       String chckFax=txtFaxNo.getText();

    Pattern pattern = Pattern.compile("^[0-9]{8}$");
    Matcher matchPattern=pattern.matcher(chckFax);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid Fax No.! ");   
    } // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNoFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
    String chckFax=txtFaxNo.getText();

    Pattern pattern = Pattern.compile("^[a-zA-Z0-9-.@]{0,50}$");
    Matcher matchPattern=pattern.matcher(chckFax);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid Email Address ! ");   
    }    
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtssnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtssnFocusLost
    String chckssn=txtssn.getText();

    Pattern pattern = Pattern.compile("^[0-9]{9}$");
    Matcher matchPattern=pattern.matcher(chckssn);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid SSN ! ");   
    }  // TODO add your handling code here:
    }//GEN-LAST:event_txtssnFocusLost

    private void txtMedicalNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalNoActionPerformed

    private void txtMedicalNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedicalNoFocusLost
    String chckMedicalNo=txtMedicalNo.getText();

    Pattern pattern = Pattern.compile("^[a-zA-Z-]{6}$");
    Matcher matchPattern=pattern.matcher(chckMedicalNo);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid Medical No. ! ");   
    }    // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalNoFocusLost

    private void txtHealthPlanNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHealthPlanNoFocusLost
    String chckHealthPlanNo=txtHealthPlanNo.getText();

    Pattern pattern = Pattern.compile("^[a-zA-Z0-9]{10}$");
    Matcher matchPattern=pattern.matcher(chckHealthPlanNo);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid Health Plan No. ! ");   
    }  

            // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthPlanNoFocusLost

    private void txtBankAccNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBankAccNoFocusLost
    String chckBankAccNo=txtBankAccNo.getText();

    Pattern pattern = Pattern.compile("^[0-9]{12}$");
    Matcher matchPattern=pattern.matcher(chckBankAccNo);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid Bank Acc No. ! ");   
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccNoFocusLost

    private void txtVehicleIdentifierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleIdentifierFocusLost
    String chckVehicleIdentifier=txtVehicleIdentifier.getText();

    Pattern pattern = Pattern.compile("^[a-zA-Z0-9]{1,50}$");
    Matcher matchPattern=pattern.matcher(chckVehicleIdentifier);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid Vehicle Identifier ! ");   
    }       // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdentifierFocusLost

    private void txtCertificateNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCertificateNoFocusLost
     String chckCertificateNo=txtCertificateNo.getText();

    Pattern pattern = Pattern.compile("^[a-zA-Z0-9]{5,10}$");
    Matcher matchPattern=pattern.matcher(chckCertificateNo);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid Certificate No ! ");   
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificateNoFocusLost

    private void txtDeviceIdentifierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeviceIdentifierFocusLost
     String chckDeviceIdentifier=txtDeviceIdentifier.getText();

    Pattern pattern = Pattern.compile("^[0-9]{4}");
    Matcher matchPattern=pattern.matcher(chckDeviceIdentifier);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid Device Identifier ! ");   
    }       // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdentifierFocusLost

    private void txtLinkedInFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLinkedInFocusLost
     String chckLinkedIn=txtLinkedIn.getText();

    Pattern pattern = Pattern.compile("^[a-zA-Z- ]{1,50}$");
    Matcher matchPattern=pattern.matcher(chckLinkedIn);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid LinkedIn name ! ");   
    }   // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInFocusLost

    private void txtipaddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtipaddressFocusLost
     String chckipaddress=txtipaddress.getText();

    Pattern pattern = Pattern.compile("^[0-9]{0,3}.[0-9]{0,3}.[0-9]{0,3}.[0-9]{0,3}$");
    Matcher matchPattern=pattern.matcher(chckipaddress);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid IP Address ! ");   
    }    // TODO add your handling code here:
    }//GEN-LAST:event_txtipaddressFocusLost

    private void txtuidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuidFocusLost
     String chckuid=txtuid.getText();

    Pattern pattern = Pattern.compile("^[0-9]{15}$");
    Matcher matchPattern=pattern.matcher(chckuid);
    if(!matchPattern.matches())
    {
     JOptionPane.showMessageDialog(this,"Please enter a valid UID ! ");   
    }   // TODO add your handling code here:
    }//GEN-LAST:event_txtuidFocusLost
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jPhoto;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBankAccNo;
    private javax.swing.JLabel lblCertificateNo;
    private javax.swing.JLabel lblDeviceIdentifier;
    private javax.swing.JLabel lblDoB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblHealthPlanNo;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedicalNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleIdentifier;
    private javax.swing.JLabel lblipaddress;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbluidCode;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBankAccNo;
    private javax.swing.JTextField txtCertificateNo;
    private javax.swing.JTextField txtDeviceIdentifier;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtHealthPlanNo;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedicalNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhNo;
    private javax.swing.JTextField txtVehicleIdentifier;
    private javax.swing.JTextField txtipaddress;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtuid;
    // End of variables declaration//GEN-END:variables
}
